# Generated by Django 6.0.3 on 2026-03-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='paciente.paciente'),
        ),
    ]
