# Generated by Django 6.0.4 on 2026-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
