from datetime import date
import random

from assistido.models import Assistido

data = [
    {
        "nome": "JOAO CARLOS SILVA",
        "nascimento": "1980-03-15",
        "sexo": "M",
        "cep": "49055-120",
        "telefone": "(79) 99811-2233",
        "endereco": "Rua José de Alencar",
        "numero": "120",
        "complemento": "APT 201",
        "bairro": "Grageru",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Assistido com acompanhamento mensal.",
        "ativo": True
    },
    {
        "nome": "MARIA HELENA DE SOUZA",
        "nascimento": "1968-07-21",
        "sexo": "F",
        "cep": "49037-240",
        "telefone": "(79) 99122-3344",
        "endereco": "Avenida Beira Mar",
        "numero": "455",
        "complemento": "CASA",
        "bairro": "13 de Julho",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Necessita visitas quinzenais.",
        "ativo": True
    },
    {
        "nome": "CARLOS EDUARDO LIMA",
        "nascimento": "1992-11-02",
        "sexo": "M",
        "cep": "49060-540",
        "telefone": "(79) 99733-1122",
        "endereco": "Rua Mato Grosso",
        "numero": "89",
        "complemento": "",
        "bairro": "Siqueira Campos",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Sem observações.",
        "ativo": True
    },
    {
        "nome": "FERNANDA ALVES ROCHA",
        "nascimento": "1985-05-09",
        "sexo": "F",
        "cep": "49100-000",
        "telefone": "(79) 99654-7788",
        "endereco": "Rua das Palmeiras",
        "numero": "300",
        "complemento": "FUNDOS",
        "bairro": "Centro",
        "cidade": "São Cristóvão",
        "estado": "SE",
        "observacoes": "Contato preferencial pela manhã.",
        "ativo": True
    },
    {
        "nome": "RICARDO MENEZES",
        "nascimento": "1977-09-18",
        "sexo": "M",
        "cep": "49095-410",
        "telefone": "(79) 99988-7766",
        "endereco": "Travessa Sergipe",
        "numero": "41",
        "complemento": "",
        "bairro": "Farolândia",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Paciente hipertenso.",
        "ativo": True
    },
    {
        "nome": "RENATA GOMES",
        "nascimento": "1990-12-11",
        "sexo": "F",
        "cep": "49080-320",
        "telefone": "(79) 98877-6655",
        "endereco": "Rua Santa Luzia",
        "numero": "900",
        "complemento": "CASA",
        "bairro": "Santos Dumont",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Necessita suporte psicológico.",
        "ativo": True
    },
    {
        "nome": "JOSE ANTONIO RIBEIRO",
        "nascimento": "1959-04-25",
        "sexo": "M",
        "cep": "49015-230",
        "telefone": "(79) 98111-4455",
        "endereco": "Rua Itabaiana",
        "numero": "77",
        "complemento": "APT 101",
        "bairro": "Centro",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Idoso com mobilidade reduzida.",
        "ativo": True
    },
    {
        "nome": "LUCIANA PRADO",
        "nascimento": "1988-08-14",
        "sexo": "F",
        "cep": "49160-000",
        "telefone": "(79) 98222-5566",
        "endereco": "Rua Principal",
        "numero": "15",
        "complemento": "",
        "bairro": "Centro",
        "cidade": "Barra dos Coqueiros",
        "estado": "SE",
        "observacoes": "Primeiro cadastro.",
        "ativo": True
    },
    {
        "nome": "MARCOS VINICIUS OLIVEIRA",
        "nascimento": "1973-10-30",
        "sexo": "M",
        "cep": "49020-150",
        "telefone": "(79) 98765-1234",
        "endereco": "Rua Bahia",
        "numero": "55",
        "complemento": "CASA",
        "bairro": "São José",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Acompanhamento social ativo.",
        "ativo": True
    },
    {
        "nome": "ALINE FERREIRA COSTA",
        "nascimento": "1995-01-19",
        "sexo": "F",
        "cep": "49045-600",
        "telefone": "(79) 98555-6677",
        "endereco": "Rua das Flores",
        "numero": "210",
        "complemento": "BLOCO B",
        "bairro": "Jardins",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Contato atualizado recentemente.",
        "ativo": True
    },
    {
        "nome": "ROBERTO SILVA NUNES",
        "nascimento": "1965-06-03",
        "sexo": "M",
        "cep": "49032-180",
        "telefone": "(79) 98444-3322",
        "endereco": "Avenida Rio Branco",
        "numero": "1000",
        "complemento": "",
        "bairro": "Getúlio Vargas",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Necessita atualização cadastral.",
        "ativo": True
    },
    {
        "nome": "CAMILA TAVARES",
        "nascimento": "2000-02-28",
        "sexo": "F",
        "cep": "49097-520",
        "telefone": "(79) 98333-9988",
        "endereco": "Rua Projetada",
        "numero": "45",
        "complemento": "CASA",
        "bairro": "Aruana",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Cadastro novo.",
        "ativo": True
    },
    {
        "nome": "PAULO HENRIQUE DIAS",
        "nascimento": "1983-11-12",
        "sexo": "M",
        "cep": "49040-220",
        "telefone": "(79) 98211-7788",
        "endereco": "Rua Minas Gerais",
        "numero": "612",
        "complemento": "APT 304",
        "bairro": "Suíssa",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Sem pendências.",
        "ativo": True
    },
    {
        "nome": "JULIANA MENDES",
        "nascimento": "1998-09-05",
        "sexo": "F",
        "cep": "49140-000",
        "telefone": "(79) 98123-4567",
        "endereco": "Rua do Comércio",
        "numero": "88",
        "complemento": "",
        "bairro": "Centro",
        "cidade": "Nossa Senhora do Socorro",
        "estado": "SE",
        "observacoes": "Assistida em programa educacional.",
        "ativo": True
    },
    {
        "nome": "ANDRE LUIZ BARBOSA",
        "nascimento": "1971-03-27",
        "sexo": "M",
        "cep": "49085-410",
        "telefone": "(79) 98989-4545",
        "endereco": "Rua Pernambuco",
        "numero": "150",
        "complemento": "CASA",
        "bairro": "América",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Necessita retorno em 30 dias.",
        "ativo": True
    },
    {
        "nome": "TATIANE OLIVEIRA SANTOS",
        "nascimento": "1987-07-17",
        "sexo": "F",
        "cep": "49047-360",
        "telefone": "(79) 97777-1111",
        "endereco": "Avenida Adélia Franco",
        "numero": "980",
        "complemento": "APT 502",
        "bairro": "Luzia",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Atualizar telefone secundário.",
        "ativo": True
    },
    {
        "nome": "FELIPE ARAUJO",
        "nascimento": "1993-04-01",
        "sexo": "M",
        "cep": "49025-730",
        "telefone": "(79) 96666-2222",
        "endereco": "Rua Paraíba",
        "numero": "321",
        "complemento": "",
        "bairro": "Industrial",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Sem observações adicionais.",
        "ativo": True
    },
    {
        "nome": "VANESSA CRISTINA LOPES",
        "nascimento": "1979-08-08",
        "sexo": "F",
        "cep": "49075-120",
        "telefone": "(79) 95555-3434",
        "endereco": "Rua João Pessoa",
        "numero": "70",
        "complemento": "CASA",
        "bairro": "Ponto Novo",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Usuária frequente do serviço.",
        "ativo": True
    },
    {
        "nome": "EDUARDO MATOS",
        "nascimento": "1962-12-24",
        "sexo": "M",
        "cep": "49035-500",
        "telefone": "(79) 94444-5656",
        "endereco": "Rua Alagoas",
        "numero": "18",
        "complemento": "FUNDOS",
        "bairro": "Novo Paraíso",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Necessita acompanhamento médico.",
        "ativo": True
    },
    {
        "nome": "BEATRIZ CARVALHO",
        "nascimento": "2001-06-10",
        "sexo": "F",
        "cep": "49052-300",
        "telefone": "(79) 93333-7878",
        "endereco": "Rua das Acácias",
        "numero": "402",
        "complemento": "APT 12",
        "bairro": "Inácio Barbosa",
        "cidade": "Aracaju",
        "estado": "SE",
        "observacoes": "Cadastro validado.",
        "ativo": True
    }
]


for item in data:
    Assistido.objects.create(
        nome=item["nome"],
        nascimento=item["nascimento"],
        sexo=item["sexo"],
        cep=item["cep"],
        telefone=item["telefone"],
        endereco=item["endereco"],
        numero=item["numero"],
        complemento=item["complemento"],
        bairro=item["bairro"],
        cidade=item["cidade"],
        estado=item["estado"],
        observacoes=item["observacoes"],
        ativo=item["ativo"]
    )