# Generated by Django 6.0.3 on 2026-03-31 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuidadora', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cuidadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuidadora', to='cuidadora.cuidadora')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
    ]
