# Generated by Django 6.0.4 on 2026-05-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('assistido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistido', to='assistido.assistido')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
    ]
