# Generated by Django 6.0.3 on 2026-03-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
