# Generated by Django 6.0.3 on 2026-03-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_escala_codigo_interno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='data',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='escala',
            name='inicio',
        ),
    ]
