# Generated by Django 6.0.3 on 2026-03-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidadora',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuidadora',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cuidadora',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidadora',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuidadora',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuidadora',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cuidadora',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
