# Generated by Django 6.0.4 on 2026-05-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('ADICIONADO_RELATORIO', 'Adicionado ao Relatório')], default='PENDENTE', max_length=20)),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegraPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HORA', 'Por Hora'), ('PLANTAO', 'Por Plantão')], default='PLANTAO', max_length=10)),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('PAGO', 'Pago')], default='ABERTO', max_length=30)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducoes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
