# Generated by Django 6.0.4 on 2026-04-22 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0002_paciente_ativo'),
        ('plantao', '0002_alter_plantao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HORA', 'Por Hora'), ('PLANTAO', 'Por Plantão')], default='PLANTAO', max_length=10)),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pagamento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='plantao.plantao')),
            ],
        ),
        migrations.CreateModel(
            name='FaixaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_min', models.FloatField()),
                ('horas_max', models.FloatField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='financeiro.regrapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('PAGO', 'Pago')], default='ABERTO', max_length=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deducoes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuidadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='paciente.paciente')),
            ],
        ),
    ]
