# Generated by Django 6.0.4 on 2026-05-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        ('plantao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='plantao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='plantao.plantao'),
        ),
    ]
