# Generated by Django 6.0.4 on 2026-04-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_pagamento_data_pagamento_and_more'),
        ('plantao', '0003_plantao_regra_pagamento_plantao_valor_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='relatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.relatorio'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='plantao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='plantao.plantao'),
        ),
    ]
