# Generated by Django 6.0.4 on 2026-05-11 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='relatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.relatorio'),
        ),
    ]
