# Generated by Django 6.0.4 on 2026-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_pagamento_relatorio_alter_pagamento_plantao'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
