# Generated by Django 6.0.4 on 2026-04-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_relatorio_codigo_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
