# Generated by Django 6.0.4 on 2026-04-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_pagamento_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regrapagamento',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
