# Generated by Django 6.0.3 on 2026-05-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_regrapagamento_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='paciente',
        ),
    ]
