# Generated by Django 6.0.3 on 2026-05-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_remove_relatorio_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='periodo_fim',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='periodo_inicio',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='data_referencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
