# Generated by Django 6.0.4 on 2026-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_alter_relatorio_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('PAGO', 'Pago'), ('RELATORIO', 'Adicionado ao Relatório')], default='ABERTO', max_length=30),
        ),
    ]
