# Generated by Django 6.0.4 on 2026-05-07 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escala', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('paciente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.DateField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('horas', models.IntegerField()),
                ('horas_cumpridas', models.FloatField(default=0)),
                ('valor_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aguarda Atendimento'), ('C', 'Confirmado'), ('R', 'Em Andamento'), ('F', 'Finalizado'), ('E', 'Expirado'), ('D', 'Desistência do Cuidador')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cuidadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.escala')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
                ('regra_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.regrapagamento')),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantões',
            },
        ),
    ]
