# Generated by Django 6.0.3 on 2026-03-31 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuidadora', '0001_initial'),
        ('escala', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('horas', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pendente de Cuidador'), ('A', 'Cuidador Aprovado'), ('C', 'Confirmado'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cuidadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuidadora.cuidadora')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.escala')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantões',
            },
        ),
    ]
