# Generated by Django 6.0.4 on 2026-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aguarda Atendimento'), ('C', 'Confirmado'), ('R', 'Em Andamento'), ('F', 'Finalizado'), ('E', 'Expirado'), ('D', 'Desistência do Cuidador')], default='A', max_length=1),
        ),
    ]
