# Generated by Django 6.0.3 on 2026-03-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente de Cuidador'), ('A', 'Cuidador Aprovado'), ('F', 'Finalizado')], default='P', max_length=1),
        ),
    ]
