# Generated by Django 6.0.4 on 2026-04-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('plantao', '0002_alter_plantao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='regra_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.regrapagamento'),
        ),
        migrations.AddField(
            model_name='plantao',
            name='valor_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
