# Generated by Django 6.0.4 on 2026-05-12 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aguarda Atendimento'), ('C', 'Confirmado'), ('R', 'Em Andamento'), ('F', 'Finalizado'), ('E', 'Expirado'), ('D', 'Desistência do Profissional')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantao.plantao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Plantão',
                'verbose_name_plural': 'Histórico de Plantões',
                'ordering': ['-created_at'],
            },
        ),
    ]
