# Generated by Django 6.0.3 on 2026-04-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0002_alter_plantao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='horas_cumpridas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plantao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente de Cuidador'), ('A', 'Cuidador Aprovado'), ('C', 'Confirmado'), ('R', 'Em Andamento'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
