# Generated by Django 6.0.4 on 2026-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0003_plantao_horas_cumpridas_alter_plantao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plantao',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente de Cuidador'), ('A', 'Aguarda Atendimento'), ('C', 'Confirmado'), ('R', 'Em Andamento'), ('F', 'Finalizado'), ('E', 'Expirado')], default='A', max_length=1),
        ),
    ]
