# Generated by Django 6.0.4 on 2026-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0003_plantao_regra_pagamento_plantao_valor_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
