# Generated by Django 6.0.4 on 2026-04-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0004_plantao_codigo_interno_alter_plantao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantao',
            name='codigo_interno',
        ),
    ]
