# Generated by Django 6.0.4 on 2026-05-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Início'), ('F', 'Fim')], max_length=1)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precisao', models.FloatField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='plantao.plantao')),
            ],
            options={
                'verbose_name': 'Registro de Plantões',
                'verbose_name_plural': 'Registro de Plantões',
                'ordering': ['data_hora'],
            },
        ),
    ]
