# Generated by Django 6.0.3 on 2026-04-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoplantao',
            options={'ordering': ['data_hora'], 'verbose_name': 'Registro de Plantões', 'verbose_name_plural': 'Registro de Plantões'},
        ),
        migrations.AddField(
            model_name='eventoplantao',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
